apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  releaseName: loki-stack
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "2.3.1"
      interval: 1m
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        storageClassName: "local-path"
        size: 5Gi
    promtail:
      enabled: true
    fluent-bit:
      enabled: false
    grafana:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - "monitoring-10-25-30-6.nip.io"
    prometheus:
      enabled: true
      alertmanager:
        persistentVolume:
          enabled: false
      server:
        persistentVolume:
          enabled: false
    filebeat:
      enabled: false
    logstash:
      enabled: false
