apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: "0.10.x"
      interval: 1m
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 110.25.30.6-10.25.30.8
