apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clearml
  namespace: clearml
spec:
  interval: 5m
  releaseName: clearml
  chart:
    spec:
      chart: clearml-server-cloud-ready
      sourceRef:
        kind: HelmRepository
        name: allegroai
        namespace: flux-system
      version: "2.0.2+1"
      interval: 1m
  values:
    ingress:
      enabled: true
      name: clearml-server-ingress
      host: "clearml.namecheapcloud.net"
      annotations:
        kubernetes.io/ingress.class: "nginx"

    apiserver:
      storage:
        logs:
          class: "local-path"
          size: 10Gi
        config:
          class: "local-path"
          size: 1Gi

    fileserver:
      storage:
        data:
          class: "local-path"
          size: 50Gi
        logs:
          class: "local-path"
          size: 5Gi

    agentservices:
      storage:
        data:
          class: "local-path"
          size: 50Gi

    agentGroups:
      - name: agent-group0
        queues: "default"
        agentVersion: ""
        replicaCount: 4
        nvidiaGpusPerAgent: 0
        clearmlApiHost: "http://clearml-apiserver:8008"
        clearmlWebHost: "http://clearml-webserver"
        clearmlFilesHost: "http://clearml-fileserver:8081"
        clearmlConfig: |-
          sdk {
              aws {
                  s3 {
                      key: ""
                      secret: ""
                      region: ""
                      credentials: [
                          {
                              host: "minio.minio:9000"
                              key: "DEMOaccessKey"
                              secret: "DEMOsecretKey"
                              multipart: false
                              secure: false
                              region: ""
                          }
                      ]
                  }
                  boto3 {
                      pool_connections: 512
                      max_multipart_concurrency: 16
                  }
              }
              development {
                  default_output_uri: "s3://minio.minio:9000/clearml/"
              }
          }

        image:
          repository: "nvidia/cuda"
          pullPolicy: IfNotPresent
          tag: "11.0-base-ubuntu18.04"

      - name: agent-group1
        queues: "gpu"
        agentVersion: ""
        replicaCount: 1
        nvidiaGpusPerAgent: 1
        clearmlApiHost: "http://clearml-apiserver:8008"
        clearmlWebHost: "http://clearml-webserver"
        clearmlFilesHost: "http://clearml-fileserver:8081"
        clearmlConfig: |-
          sdk {
              aws {
                  s3 {
                      key: ""
                      secret: ""
                      region: ""
                      credentials: [
                          {
                              host: "minio.minio:9000"
                              key: "DEMOaccessKey"
                              secret: "DEMOsecretKey"
                              multipart: false
                              secure: false
                              region: ""
                          }
                      ]
                  }
                  boto3 {
                      pool_connections: 512
                      max_multipart_concurrency: 16
                  }
              }
              development {
                  default_output_uri: "s3://minio.minio:9000/clearml/"
              }
          }

        image:
          repository: "nvidia/cuda"
          pullPolicy: IfNotPresent
          tag: "11.0-base-ubuntu18.04"
    
    redis:
      master:
        persistence:
          storageClass: "local-path"
    
    mongodb:
      persistence:
        storageClass: "local-path"
    
    elasticsearch:
      volumeClaimTemplate:
        storageClassName: "local-path"
      extraEnvs:
        - name: bootstrap.memory_lock
          value: "false"
        - name: cluster.routing.allocation.node_initial_primaries_recoveries
          value: "500"
        - name: cluster.routing.allocation.disk.watermark.low
          value: 500mb
        - name: cluster.routing.allocation.disk.watermark.high
          value: 500mb
        - name: cluster.routing.allocation.disk.watermark.flood_stage
          value: 500mb
        - name: http.compression_level
          value: "7"
        - name: reindex.remote.whitelist
          value: '*.*'
        - name: xpack.monitoring.enabled
          value: "false"
        - name: xpack.security.enabled
          value: "false"