apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 5m
  releaseName: gpu-operator
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: nvidia-gpu-operator
        namespace: flux-system
      version: "1.8.x"
      interval: 1m
  values:
    operator:
      defaultRuntime: containerd
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
